# Generated by Django 4.0.6 on 2022-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyId', models.AutoField(primary_key=True, serialize=False)),
                ('DefCurrency', models.CharField(max_length=500)),
                ('LastUpdDate', models.CharField(max_length=500)),
                ('CurrencyValues', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Currency',
                'managed': True,
            },
        ),
    ]
