# Generated by Django 4.0.6 on 2022-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('ValueId', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('CurrencyValue', models.FloatField(max_length=500)),
                ('LastUpdDate', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Currency',
                'db_table': 'Currency',
                'managed': True,
            },
        ),
    ]
