# Generated by Django 4.0.6 on 2022-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='def_currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
